openapi: 3.0.2
info:
  title: Sustainable Mobility API
  version: 1.0.0
  description: >-
    Promoting sustainable transportation systems by providing transparency into
    the environmental costs of transport journeys.
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0"
  contact:
    name: Brylie Christopher Oxley
    email: brylie.oxley@maas.global
servers:
  - url: /
    description: Local server relative to documentation server.
paths:
  /estimate-co2:
    summary: Estimate CO2 emissions for one or more transportation legs.
    description: >-
      This endpoint will return an estimation of CO2 impact of one or more
      transport legs, provided origin and destination (or pre-calculated
      distance in kilometers), and transportation mode for each leg. The leg
      vehicle occupancy can be overridden when it is not desirable to use an average value.

      Design rationale: Journey planners may need to annotate multiple itinerary options with
      CO2 estimates. The HTTP overhead for multiple annotations may add
      unreasonable delay to the overall journey planner result. This endpoint
      reduces the network overhead by allowing multiple CO2 estimations to be
      produced by a single HTTP request.
    post:
      operationId: api.get_co2_estimate
      summary: Get an estimate of CO2 emissions for one or more transport legs.
      description: >-
        Provided with origin and destination (or pre-calculated distance in
        kilometers), and transport mode, this endpoint will estimate CO2
        emissions for one or more transport legs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                oneOf:
                  - $ref: "#/components/schemas/itinerary_option_origin_destination"
                  - $ref: "#/components/schemas/itinerary_option_distance_km"
      responses:
        "200":
          description: >-
            This contains an array of objects each containing an estimate of CO2 emissions in grams for the given
            transportation leg. Where the CO2 estimation was not possible, an error object will be returned with
            a description of the issue in the `error_message` field.
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - oneOf:
                        - $ref: "#/components/schemas/co2_estimate"
                        - $ref: "#/components/schemas/error"
components:
  links: {}
  callbacks: {}
  schemas:
    coordinate:
      type: object
      description: A geographic coordinate with latitude and longitude in WGS-84 decimal degrees.
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
      required:
        - latitude
        - longitude
    itinerary_option_origin_destination:
      type: object
      description: Itinerary option where the trip origin and destination coordinates are known. Using WGS-84 lat/long.
      properties:
        transport_mode:
          $ref: "#/components/schemas/transport_mode"
        origin:
          $ref: "#/components/schemas/coordinate"
        destination:
          $ref: "#/components/schemas/coordinate"
        vehicle_occupancy:
          type: number
      required:
        - transport_mode
        - origin
        - destination
      additionalProperties: true
      example:
        origin:
          latitude: 60.2055
          longitude: 24.9384
        destination:
          latitude: 60.2055
          longitude: 24.6559
        other_property: "something else"
    itinerary_option_distance_km:
      type: object
      description: Itinerary option where the trip distince in kilometers is provided.
      properties:
        transport_mode:
          $ref: "#/components/schemas/transport_mode"
        distance_km:
          type: number
        distance_km:
          type: number
      required:
        - transport_mode
        - distance_km
      additionalProperties: true
    transport_mode:
      type: string
      enum:
        - LIGHT_RAIL
        - SMALL_CAR
        - LARGE_CAR
        - SCOOTER
        - BUS
        - WALK
        - BICYCLE
        - CAR
        - TRAM
        - SUBWAY
        - RAIL
        - FERRY
        - CABLE_CAR
        - GONDOLA
        - FUNICULAR
        - TRANSIT
        - LEG_SWITCH
        - AIRPLANE
    co2_estimate:
      type: object
      description: An estimate of grams CO2 for the given transportation leg.
      example:
        transport_mode: "SMALL_CAR"
        vehicle_occupancy: 2
        distance_km: 20
        estimated_co2_g: 200
    error:
      type: object
      description: Error details about why CO2 estimation failed for this specific leg.
      properties:
        error_message:
          type: string
security: []
